# Generated by Django 5.1.7 on 2025-05-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='prenom',
        ),
    ]
