# Generated by Django 5.1.7 on 2025-05-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_medecin_email_remove_medecin_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
